server:
  port: 8080
spring.data.mongodb.database: bluewater
spring.data.mongodb.uri:
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG