# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dev-bluewater-web-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_f9ae62a81a9a4349b6f87f014387f41a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5cc59f1ec3bb42dba59ba1808064062f }}

    - name: Make jar file
      run: |
        ./gradlew clean build

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f9ae62a81a9a4349b6f87f014387f41a }}/openjdk:${{ github.sha }}
        file: ./Dockerfile


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dev-bluewater-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1b260074f41347b08b3c38af181a1aaf }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_f9ae62a81a9a4349b6f87f014387f41a }}/openjdk:${{ github.sha }}'
