# workflow for CI
name: CI build workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Adding secret
      run: |
        printf ${{secrets.COSMOS_SECRET_URI}} >> src/main/resources/application.yml
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean build